export const GENERAL = {
  NAME_COMPONENT: '::microservice-access::',
  MESSAGE_SUCCEFULL: 'Proceso exitoso',
  STATUS_CREATED: 'Creado',
  EXCEPTION_CODE: {
    GENERATE_TOKEN: '[ER-GTHS]',
    REGISTER_SECURITY: '[ER-RSFU]',
    FIND_SECURITY_TOKEN: '[ER-FSBT]',
    DELETE_SECURITY_TOKEN: '[ER-DSTE]',
    REGISTER_LOG_ACCESS: '[ER-RLACC]',
    REGISTER_HOME_CONSULTING: '[ER-HMCL]',
    REGISTER_HOME_SESSION: '[ER-HMSS]',
  },
  ACCESS: {
    LOGIN_CODE: 'LOGIN',
    LOGOUT_CODE: 'LOGOUT',
  },
  CLIENT: {
    LOGS: 'CLIENT_LOGS',
    ACCESS: 'CLIENT_ACCESS',
  },
};
