name: ci_cd_microservice_access

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USSERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker buildx create --use
        docker buildx inspect --bootstrap
        docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USSERNAME }}/microservice-access:latest -t ${{ secrets.DOCKER_USSERNAME }}/microservice-access:latest .
        docker push ${{ secrets.DOCKER_USSERNAME }}/microservice-access:latest

    - name: Logout from Docker Hub
      run: docker logout